swagger: '2.0'
info:
  title: Reino Trebol
  description: >-
    En el Reino del Trébol, El Rey Mago requiere diseñar un sistema para la academia de magia; este debe realizar el registro de solicitud del estudiante y la asignación aleatoria de su Grimorio.
  version: 1.0.11
host: ia.interactive.com.mx:8080
basePath: /ia/interactive/alumnos/v1
schemes:
  - https
produces:
  - application/json

securityDefinitions:
  Bearer:
    description: |-
      Para acceder a la API se debe pasar un token válido en todas las consultas. La siguiente sintaxis se debe utilizar en el encabezado con nombre 'Token':
      
        Bearer: 123
    type: apiKey
    name: Token
    in: header

paths:
  /alumnos/{id}:
    put:
      description: Actualiza alumnos.
      summary: Actualiza alumnos.
      tags:
        - Alumnos
      parameters:
        - name: id
          in: path
          description: Actualiza alumnos
          required: true
          type: integer
          default: 1
        - in: body
          name: body
          description: Datos requeridos para el agregado de un toque a un cliente.
          required: true
          schema:
            $ref: '#/definitions/registrados'
      responses:
        '200':
          description: Operación exitosa
          schema:
            $ref: '#/definitions/respuesta'
        '400':
          description: "Identificador invalido"
        '404':
          description: "Alumno no encontrado"
        '500':
          description: "Error inesperado."

    delete:
      description: Elimina alumnos.
      summary: Elimina alumnos.
      tags:
        - Alumnos
      parameters:
        - name: id
          in: path
          description: Elimina alumnos
          required: true
          type: integer
          default: 1
      responses:
        '200':
          description: Operación exitosa
          schema:
            $ref: '#/definitions/respuesta'
        '400':
          description: "Identificador invalido"
        '404':
          description: "Alumno no encontrado"
        '500':
          description: "Error inesperado."

  /alumnos:
    get:
      description: Muestra alumnos registrados.
      summary: Muestra alumnos registrados.
      tags:
        - Alumnos
      responses:
        '200':
          description: Operación exitosa
          schema:
            $ref: '#/definitions/alumnosRegistrados'
        '400':
          description: "Identificador invalido"
        '500':
          description: "Error inesperado."

    post:
      description: Agrega alumnos nuevos.
      summary: Agrega alumnos nuevos.
      tags:
        - Alumnos
      consumes:
        - application/json
      parameters:
        - in: body
          name: body
          schema:
            $ref: '#/definitions/alumnos'
      responses:
        '200':
          description: "Operación exitosa"
          schema:
            $ref: '#/definitions/respuesta'
        '400':
          description: "Identificador invalido"
        '500':
          description: "Error inesperado."

  /grimorios:
    get:
      description: Muestra los grimorios.
      summary: Muestra los grimorios.
      tags:
        - Grimorios
      responses:
        '200':
          description: Operación exitosa
          schema:
            $ref: '#/definitions/grimorios'
        '400':
          description: "Identificador invalido"
        '500':
          description: "Error inesperado."

definitions:
  respuesta:
    type: object
    properties:
      mensaje:
        type: string
        description: Mensaje de la operación.
        example: 'Operación exitosa.'
      folio:
        type: string
        description: Folio de respuesta.
        example: '1234'
          
  alumnos:
    type: object
    properties:
      id:
        type: integer
        format: int64
        example: 10
      nombre:
        type: string
        example: 'theUser'
      apellido:
        type: string
        example: 'John'
      identificacion:
        type: string
        example: 'JAJA000'
      edad:
        type: number
        example: 30
          
  alumnosRegistrados:
    type: object
    properties:
      mensaje:
        type: string
        description: Mensaje de la operacion.
        example: 'Operación exitosa.'
      folio: 
        type: string
        description: Folio de respuesta.
        example: '1234' 
      alumnos:
        type: array
        items:
          type: object
          properties:
            id:
              type: integer
              format: int64
              example: 10
            nombre:
              type: string
              example: 'theUser'
            apellido:
              type: string
              example: 'John'
            identificacion:
              type: string
              example: 'JAJA000'
            edad:
              type: number
              example: 30
            afinidad_magica:
              type: string
              example: 'Magia de Niebla'
            grimorio:
              type: string
              example: 'Amor – Trébol de 3 hojas'
  grimorios:
    type: object
    properties:
      mensaje:
        type: string
        description: Mensaje de la operacion.
        example: 'Operación exitosa.'
      folio: 
        type: string
        description: Folio de respuesta.
        example: '1234' 
      grimorios:
        type: array
        items:
          type: object
          properties:
            id:
              type: integer
              format: int64
              example: 10
            afinidad_magica:
              type: string
              example: 'Magia de Niebla'
            grimorio:
              type: string
              example: 'Amor – Trébol de 3 hojas'
    
  registrados:
    type: object
    properties:
      id:
        type: integer
        format: int64
        example: 10
      nombre:
        type: string
        example: 'theUser'
      apellido:
        type: string
        example: 'John'
      identificacion:
        type: string
        example: 'JAJA000'
      edad:
        type: number
        example: 30
      afinidad_magica:
        type: string
        example: 'Magia de Niebla'
      grimorio:
        type: string
        example: 'Amor – Trébol de 3 hojas'
              
  summary:
    type: object
    properties: 
      api-name: 
        type: string
        description: "En el Reino del Trébol, El Rey Mago requiere diseñar un sistemapara la academia de magia; este debe realizar el registro de solicitud delestudiante y la asignación aleatoria de su Grimorio.."
        example: "ia-interactive-reino-trebol"
      alumnos-id-put:
        type: object
        properties:
          displayName:
            type: string
            description: "Actualiza alumnos."
            example: "Actualiza alumnos."   
      alumnos-id-delete:
        type: object
        properties:
          displayName:
            type: string
            description: "Elimina alumnos."
            example: "Elimina alumnos."
      alumnos-get:
        type: object
        properties:
          displayName:
            type: string
            description: "Muestra alumnos registrados."
            example: "Muestra alumnos registrados." 
      alumnos-post:
        type: object
        properties:
          displayName:
            type: string
            description: "Agrega alumnos nuevos."
            example: "Agrega alumnos nuevos." 
      grimorios-get:
        type: object
        properties:
          displayName:
            type: string
            description: "Muestra los grimorios."
            example: "Muestra los grimorios." 